using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace CommunityGiving.Api.Services;

public interface IPdfDocumentService
{
    byte[] GenerateReceiptPdf(ReceiptPdfModel model);
    byte[] GenerateInvoicePdf(InvoicePdfModel model);
}

public record ReceiptPdfModel(string OrgName, string? OrgAddress, string ReceiptNumber, DateTime IssuedAtUtc,
    string DonorName, string DonorEmail, string FundName, decimal Amount, string Currency, string? FooterText);

public record InvoiceLineItemPdfModel(string Description, int Quantity, decimal UnitPrice);
public record InvoicePdfModel(string OrgName, string? OrgAddress, string InvoiceNumber, DateOnly IssueDate,
    DateOnly DueDate, string BillToName, string BillToEmail, List<InvoiceLineItemPdfModel> LineItems,
    string? Notes, string? PaymentLinkUrl);

public class PdfDocumentService : IPdfDocumentService
{
    public PdfDocumentService()
    {
        // Community (free) license for QuestPDF — required by the library as of v2023+.
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public byte[] GenerateReceiptPdf(ReceiptPdfModel m)
    {
        var doc = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A5);
                page.Margin(30);
                page.DefaultTextStyle(t => t.FontSize(11));

                page.Header().Column(col =>
                {
                    col.Item().Text(m.OrgName).FontSize(18).Bold();
                    if (!string.IsNullOrWhiteSpace(m.OrgAddress)) col.Item().Text(m.OrgAddress).FontSize(9).FontColor(Colors.Grey.Darken1);
                    col.Item().PaddingTop(8).Text("Donation Receipt").FontSize(14).SemiBold();
                });

                page.Content().PaddingVertical(15).Column(col =>
                {
                    col.Spacing(6);
                    col.Item().Text($"Receipt #: {m.ReceiptNumber}");
                    col.Item().Text($"Date: {m.IssuedAtUtc:MMMM d, yyyy}");
                    col.Item().PaddingTop(10).Text($"Received from: {m.DonorName}");
                    col.Item().Text($"Email: {m.DonorEmail}");
                    col.Item().PaddingTop(10).Text($"Fund: {m.FundName}");
                    col.Item().Text($"Amount: {m.Amount:0.00} {m.Currency.ToUpper()}").FontSize(14).Bold();
                    col.Item().PaddingTop(15).Text("Thank you for your generous contribution.");
                    if (!string.IsNullOrWhiteSpace(m.FooterText))
                        col.Item().PaddingTop(15).Text(m.FooterText).FontSize(9).FontColor(Colors.Grey.Darken1);
                });

                page.Footer().AlignCenter().Text(t =>
                {
                    t.Span("Generated by the Community Giving Platform").FontSize(8).FontColor(Colors.Grey.Medium);
                });
            });
        });

        return doc.GeneratePdf();
    }

    public byte[] GenerateInvoicePdf(InvoicePdfModel m)
    {
        var total = m.LineItems.Sum(l => l.Quantity * l.UnitPrice);

        var doc = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(35);
                page.DefaultTextStyle(t => t.FontSize(11));

                page.Header().Column(col =>
                {
                    col.Item().Text(m.OrgName).FontSize(20).Bold();
                    if (!string.IsNullOrWhiteSpace(m.OrgAddress)) col.Item().Text(m.OrgAddress).FontSize(9).FontColor(Colors.Grey.Darken1);
                    col.Item().PaddingTop(10).Text("Invoice").FontSize(16).SemiBold();
                });

                page.Content().PaddingVertical(15).Column(col =>
                {
                    col.Spacing(4);
                    col.Item().Row(row =>
                    {
                        row.RelativeItem().Column(c =>
                        {
                            c.Item().Text("Bill to:").FontColor(Colors.Grey.Darken1).FontSize(9);
                            c.Item().Text(m.BillToName).Bold();
                            c.Item().Text(m.BillToEmail);
                        });
                        row.RelativeItem().AlignRight().Column(c =>
                        {
                            c.Item().Text($"Invoice #: {m.InvoiceNumber}");
                            c.Item().Text($"Issue date: {m.IssueDate:MMM d, yyyy}");
                            c.Item().Text($"Due date: {m.DueDate:MMM d, yyyy}").Bold();
                        });
                    });

                    col.Item().PaddingTop(20).Table(table =>
                    {
                        table.ColumnsDefinition(cols =>
                        {
                            cols.RelativeColumn(4);
                            cols.RelativeColumn(1);
                            cols.RelativeColumn(2);
                            cols.RelativeColumn(2);
                        });

                        table.Header(header =>
                        {
                            header.Cell().Text("Description").Bold();
                            header.Cell().Text("Qty").Bold();
                            header.Cell().Text("Unit price").Bold();
                            header.Cell().Text("Amount").Bold();
                            header.Cell().ColumnSpan(4).PaddingTop(3).BorderBottom(1).BorderColor(Colors.Grey.Lighten1);
                        });

                        foreach (var item in m.LineItems)
                        {
                            table.Cell().PaddingVertical(3).Text(item.Description);
                            table.Cell().PaddingVertical(3).Text(item.Quantity.ToString());
                            table.Cell().PaddingVertical(3).Text($"{item.UnitPrice:0.00}");
                            table.Cell().PaddingVertical(3).Text($"{item.Quantity * item.UnitPrice:0.00}");
                        }
                    });

                    col.Item().PaddingTop(10).AlignRight().Text($"Total due: {total:0.00}").FontSize(14).Bold();

                    if (!string.IsNullOrWhiteSpace(m.PaymentLinkUrl))
                        col.Item().PaddingTop(15).Text($"Pay online: {m.PaymentLinkUrl}").FontColor(Colors.Blue.Darken2);

                    if (!string.IsNullOrWhiteSpace(m.Notes))
                        col.Item().PaddingTop(15).Text(m.Notes).FontSize(9).FontColor(Colors.Grey.Darken1);
                });

                page.Footer().AlignCenter().Text(t =>
                {
                    t.Span("Generated by the Community Giving Platform").FontSize(8).FontColor(Colors.Grey.Medium);
                });
            });
        });

        return doc.GeneratePdf();
    }
}
